### ISSUE TITLE
Issues about funtion definition

### ISSUE THREAD

**Issue by zhangerjun** [brainhack-school2020/BHS_Project_dMRI#2]
I found it is a little strange to define a funtion in Jupyter notebook. 

- It can work well when I define a fution in jupyter notebook. However, once I creat a new py funtion file, use %file_name, it can not work. The same problem when I use load to use this function. Does anyone know the reason?

- If the funtion is with many lines. Can I put the function part at the end of jupyter notebook file in order to make the code more condense? Or is there any standards about funtions definition in jupyter notebook? Thanks.

**Comment by gkiar** [comment]
Hi @zhangerjun - thanks for the question!

So, in general I'll state this warning: avoid as many `%file_name`-type lines (i.e jupyter syntax that starts with a `%`) as **possible**. The main reason being that they aren't real Python syntax, so wouldn't work as soon as you try to move all of your code into a script.

The easiest *correct* way to define and import functions for your application would then be:
- Create a `.py` file in the same directory as your notebook
- Create an empty `__init__.py` file in that same directory. This file doesn't need any content, just to exist, and then Python will know to look nearby for functions/modules it can import.
- Import it at the top of your notebook/another Python script in your directory with standard syntax, i.e. `from myfile import myfunction` or `from myfile import *` or `import myfile` or `import myfile as awesome`.

Sounds like you should be pretty close already if you have it in a `.py` file! Does that make sense?

**Comment by zhangerjun** [comment]
Thanks @gkiar . I have not  created __init__.py file yet. This might be the reason why funtion define can work in jupyter notebook but can not work if I use myfuntion.py. Thanks, let me try.

**Comment by zhangerjun** [comment]
Thanks @gkiar , it works!
